### ISSUE TITLE
Does the backend storage driver support native filesystem?

### ISSUE THREAD

**Issue by CodeJuan** [containerops/dockyard#108]
![](https://github.com/containerops/dockyard/raw/master/docs/arch.png)
In the arch diagram, I saw that the backend storage driver doesn't support native filesystem. 
I am wondering if is there any method to use native filesystem as backend storage?

Thanks a lot 
^_^

**Comment by MabinGo** [comment]
Hi CodeJuan, Dockyard uses native filesystem as the default storage,so that we can be easy to get and analyze the images context.
