### ISSUE TITLE
rkt test error:  `x509: certification signed by unkonw authority`

### ISSUE THREAD

**Issue by liangchenye** [containerops/dockyard#111]
Hi, 
When I test rkt on Dockyard, I always received the x509 error.
Setup to reproduce
1. build and run the new Dockyard (with cert file updated)
2. follow the rkt image creating instruction 
    (https://github.com/liangchenye/dockyard/blob/rkttest/test/rkt/README.MD)
3. run the test

PS:
the docker push/pull works good.

(https://github.com/containerops/dockyard/pull/110)

**Comment by liangchenye** [comment]
@genedna  @MabinGo 
Confirmed with Zhouhu, he also saw this error.

**Comment by MabinGo** [comment]
@liangchenye Thanks for your reminder, this error is associated with old certificate,I will try to solve it asap,erenow,you can add flag "--insecure=true" when you execute acpush to continue your test.

**Comment by genedna** [comment]
@liangchenye @MabinGo 

I generated containerops.crt file with wrong INTERMEDIATE section caused this bug and I already updated the file in c9b239d00f63015f4213f8a6f27e3c329ed15dc2.

`--insecure=true` don't need in _rkt_ and _docker_ client, please try again.
