### ISSUE TITLE
'undefined: config.ConfigContainer' when building Dockyard

### ISSUE THREAD

**Issue by insertjokehere** [containerops/dockyard#113]
Hi,

I'm trying to build Dockyard so I can test if it will work in my environment, but I keep getting the following error: "src/github.com/containerops/wrench/setting/setting.go:16: undefined: config.ConfigContainer".

The process I'm following is:

* Fetch a golang environment using Docker: ````docker pull golang:1.6````
* Run a container to build: ````docker run -ti golang:1.6 /bin/bash````
* Inside the container, follow the instructions from the README:
````
go get github.com/containerops/dockyard
cd $GOPATH/src/github.com/containerops/dockyard
go build
````

After the 'go get' command, I get the error as above. I have tried with both the golang:1.6 and golang:1.5 images, but with the same result. Any suggestions?

Thanks

**Comment by genedna** [comment]
@insertjokehere 

The master branch depend on old beego config library causes the failure of building. I already merged the newest code from develop branch, and please try again.

We support `godep` also, or try like this:
```
godep go build
```

**Comment by insertjokehere** [comment]
Thanks, can confirm this fixed my problem
