### ISSUE TITLE
dockyard expects mysql to have a database dockyard already created

### ISSUE THREAD

**Issue by rmartinez3** [containerops/dockyard#122]
I'm trying to get dockyard up and running. I started up a mysql instance. However, dockyard logs that it was not able to find a dockyard database in mysql. This error keeps coming up until I create the database itself. I think this is something that dockyard should do. Create the database if not present. If its present then just connect to it.

**Comment by MabinGo** [comment]
Hi rmartinez3, thanks for your good suggestion,we are doing as you said now.

**Comment by MabinGo** [comment]
New feature is commited to develop branch.This issue would be closed.
